<!DOCTYPE html>
<html lang="PT-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Celsius e Fahrenheit</title>
</head>

<body>
    <form action="dados.PHP">
        <label for="nome">Nome:</label>
        <input type="text" name="nome" placeholder="ex: Fernando">

        <label for="peso">Celsius:</label>
        <input type="number" name="Celsius" placeholder="ex: 24°c">

        <label for="altura">Fahrenheit:</label>
        <input type="number" name="Fahrenheit" placeholder="ex: 173°f">

        <button> Enviar </button>
    </form>
</body>

</html>